version: '3.9'
services:
  api:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    environment:
      - DB_PATH=/app/data/db.sqlite
    ports:
      - "3000:3000"
